"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = ['haarcascade_frontalface_default.xml', 'mlp_classifier.model', 'question-sheet.csv', 'model.h5']
OPTIONS = {'packages': ['tensorflow', 'pandas', 'keras', 'h5py', 'librosa', 'glob', 'os', 'sklearn', 'pyaudio', 'wave', 'struct', 'pickle', 'numba', 'numpy', 'llvmlite'], 'includes':['tensorflow', 'pandas', 'keras', 'h5py', 'librosa', 'glob', 'os', 'sklearn', 'pyaudio', 'wave', 'struct', 'pickle', 'numba', 'numpy', 'llvmlite']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
